name = "Floquet"
version = "0.0.0"
license = "GNU General Public License v3.0"
author = "Álvaro R. Puente-Uriona"
maintainer = "alvaro.ruiz@ehu.eus"
copyright = "Copyright 2024, Álvaro R. Puente-Uriona"

[library]
source-dir="src"

[build]
auto-executables = true
auto-tests = true
auto-examples = true
module-naming = false

[install]
library = true

[fortran]
implicit-typing = true
implicit-external = true
source-form = "free"

[dependencies]
MAC = { git="https://github.com/irukoa/MAC.git", tag = "v1.0.0" }
WannInt = { git="https://github.com/irukoa/WannInt.git", tag = "v1.0.0" }
SsTC_driver = { git="https://github.com/irukoa/SsTC_driver.git", tag = "v1.0.0" }
Extrapolation_Integration = { git="https://github.com/irukoa/Extrapolation_Integration.git", tag = "v1.0.0" }
mpi = "*"
openmp = "*"

[dev-dependencies]
test-drive.git = "https://github.com/fortran-lang/test-drive"
test-drive.tag = "v0.4.0"
